### ISSUE TITLE
Is nightly still needed?

### ISSUE THREAD

**Issue by brandonros** [darfink/detour-rs#35]
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\Brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\detour-0.8.1\src\lib.rs:4:3
  |
4 |   feature(const_fn_trait_bound, unboxed_closures, abi_thiscall)
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: the feature `const_fn_trait_bound` has been stable since 1.61.0 and no longer requires an attribute to enable

For more information about this error, try `rustc --explain E0554`.
error: could not compile `detour` due to previous error

```

**Comment by cxcubehd** [comment]
I hope that this also will be fixed soon...

**Comment by loongs-zhang** [comment]
So do I.

**Comment by loongs-zhang** [comment]
Finally, I cloned this library and modified it.

**Comment by brandonros** [comment]
@dragon-zhang i do not see your fork/branch/pull request. can you share please?

**Comment by loongs-zhang** [comment]
> @dragon-zhang i do not see your fork/branch/pull request. can you share please?

https://github.com/acl-dev/open-coroutine/tree/dev/detour2

**Comment by darfink** [comment]
Fixed in #48, which overhauls the library: it now builds on stable Rust (1.85+), replaces `libudis86-sys` with `iced-x86`, and drops `mmap-fixed`. This will be part of the upcoming 0.9.0 release.
